name: Bump dev version on dependency PR
on:
  pull_request:
    types: [closed]

jobs:
  trigger-reusable-workflow:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      contains(
        github.event.pull_request.labels.*.name,
        'dependencies'
      )
    uses: AstarVienna/DevOps/.github/workflows/bump.yml@main
    secrets: inherit
    with:
      rule: prerelease
      branch: main
