name: Minimum Dependencies
# Installs the minimum versions of the dependencies and runs the tests.
# This test will lower the chance that users botch their installation by
# only upgrading this project but not the dependencies.

on:
  push:
    branches:
      - master
      - dev_master
      - dev_spectroscopy
  pull_request:
    branches:
      - master
      - dev_master
      - dev_spectroscopy

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

  schedule:
    - # Run every day at 5:00 UTC.
    - cron: "0 5 * * *"

jobs:
  call-minimum-dependencies:
    uses: AstarVienna/DevOps/.github/workflows/minimumdependencies.yml@master
